name: PlayerVaults
main: PlayerVaults\PlayerVaults
api: [3.0.0, 3.0.0-ALPHA12, 4.0.0]
version: 2.0
commands:
  playervault:
    default: true
    aliases: ["pv"]
permissions:
  playervaults.vault.1:
    default: true
